---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.rb"
exclude_paths:
- test/
