---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
    config:
      app_path: test/dummy
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.rb"
exclude_paths:
- test/
