name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.6.x","2.5.x"]
        rails: ["6.0.2","5.2.0","5.1.0"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'
    - name: Build and test
      env: 
        RAILS_VERSION: ${{ matrix.rails }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
